class Words {
  static List words = [
    {"word": "bird", "val": 1},
    {"word": "eagle", "val": 1},
    {"word": "bat", "val": 1},
    {"word": "plane", "val": 1},
    {"word": "helicopter", "val": 1},
    {"word": "jet plane", "val": 1},
    {"word": "time", "val": 1},
    {"word": "drone", "val": 1},
    {"word": "hand glider", "val": 1},
    {"word": "rocket", "val": 1},
    {"word": "kite", "val": 1},
    {"word": "butterfly", "val": 1},
    {"word": "bee", "val": 1},
    {"word": "wasp", "val": 1},
    {"word": "air plane", "val": 1},
    {"word": "jet", "val": 1},
    {"word": "glider", "val": 1},
    {"word": "helium balloon", "val": 1},
    {"word": "crow", "val": 1},
    {"word": "glider", "val": 1},
    {"word": "nightingale", "val": 1},
    {"word": "vulture", "val": 1},
    {"word": "dragonfly", "val": 1},
    {"word": "you", "val": -1},
    {"word": "clock", "val": -1},
    {"word": "fire", "val": -1},
    {"word": "couch", "val": -1},
    {"word": "door", "val": -1},
    {"word": "pencil", "val": -1},
    {"word": "printer", "val": -1},
    {"word": "bottle", "val": -1},
    {"word": "headphone", "val": -1},
    {"word": "banana", "val": -1},
    {"word": "orange", "val": -1},
    {"word": "apple", "val": -1},
    {"word": "sandwich", "val": -1},
    {"word": "burger", "val": -1},
    {"word": "egg", "val": -1},
    {"word": "chair", "val": -1},
    {"word": "trumpet", "val": -1},
    {"word": "hat", "val": -1},
    {"word": "potato", "val": -1},
    {"word": "candle", "val": -1},
    {"word": "cow", "val": -1},
  ];
  static List numbers = [
    {"word": "1", "val": 1},
    {"word": "2", "val": -1},
    {"word": "3", "val": 1},
    {"word": "4", "val": -1},
    {"word": "5", "val": 1},
    {"word": "6", "val": -1},
    {"word": "7", "val": 1},
    {"word": "8", "val": -1},
    {"word": "nine", "val": 1},
    {"word": "10", "val": -1},
    {"word": "11", "val": 1},
    {"word": "12", "val": -1},
    {"word": "13", "val": 1},
    {"word": "14", "val": -1},
    {"word": "fifteen", "val": 1},
    {"word": "16", "val": -1},
    {"word": "17", "val": 1},
    {"word": "18", "val": -1},
    {"word": "19", "val": 1},
    {"word": "20", "val": -1},
    {"word": "two", "val": -1},
    {"word": "nine", "val": 1},
    {"word": "twenty-one", "val": 1},
    {"word": "ten", "val": -1},
    {"word": "one", "val": 1},
    {"word": "sEven", "val": 1},
    {"word": "eighteen", "val": -1},
    {"word": "thirty-one", "val": 1},
  ];
  static List colors = [
    {"word": "Red", "color": 0xFFFF0000, "val": 1},
    {"word": "Green", "color": 0xFF808080, "val": -1},
    {"word": "White", "color": 0xFF000000, "val": -1},
    {"word": "Yellow", "color": 0xFF808080, "val": -1},
    {"word": "Aqua", "color": 0xFF00FFFF, "val": 1},
    {"word": "Red", "color": 0xFF808080, "val": -1},
    {"word": "Pink", "color": 0xFFFFFF00, "val": -1},
    {"word": "Yellow", "color": 0xFF0000FF, "val": -1},
    {"word": "Aqua", "color": 0xFF800080, "val": -1},
    {"word": "Purple", "color": 0xFF800080, "val": 1},
    {"word": "Green", "color": 0xFF008000, "val": 1},
    {"word": "Black", "color": 0xFF000000, "val": 1},
    {"word": "Blue", "color": 0xFFFFA500, "val": -1},
    {"word": "Orange", "color": 0xFFFFA500, "val": 1},
  ];
}
