class Words{
  static List words=[
    {"word":"bird", "val":1},
    {"word":"eagle", "val":1},
    {"word":"bat", "val":1},
    {"word":"plane", "val":1},
    {"word":"helicopter", "val":1},
    {"word":"jet plane", "val":1},
    {"word":"time", "val":1},
    {"word":"drone", "val":1},
    {"word":"hand glider", "val":1},
    {"word":"rocket", "val":1},
    {"word":"kite", "val":1},
    {"word":"butterfly", "val":1},
    {"word":"bee", "val":1},
    {"word":"wasp", "val":1},
    {"word":"air plane", "val":1},
    {"word":"jet", "val":1},
    {"word":"glider", "val":1},
    {"word":"helium balloon", "val":1},
    {"word":"crow", "val":1},
    {"word":"glider", "val":1},
    {"word":"nightingale", "val":1},
    {"word":"vulture", "val":1},
    {"word":"dragonfly", "val":1},
    {"word":"you", "val":-1},
    {"word":"clock", "val":-1},
    {"word":"fire", "val":-1},
    {"word":"couch", "val":-1},
    {"word":"door", "val":-1},
    {"word":"pencil", "val":-1},
    {"word":"printer", "val":-1},
    {"word":"bottle", "val":-1},
    {"word":"headphone", "val":-1},
    {"word":"banana", "val":-1},
    {"word":"orange", "val":-1},
    {"word":"apple", "val":-1},
    {"word":"sandwich", "val":-1},
    {"word":"burger", "val":-1},
    {"word":"egg", "val":-1},
    {"word":"chair", "val":-1},
    {"word":"trumpet", "val":-1},
    {"word":"hat", "val":-1},
    {"word":"potato", "val":-1},
    {"word":"candle", "val":-1},
    {"word":"cow", "val":-1},
  ];
}
